name: fake_factory
description: Generate fake objects.
version: 0.0.1
repository:

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    build: ^2.1.0
    faker: ^2.0.0

dev_dependencies:
    build_runner: ^2.1.2
    flutter_lints: ^1.0.0
    source_gen: ^1.1.0
    source_gen_test: ^1.0.1
    test: ^1.17.12
